/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.TableModelItemCompra;
import domain.ItemCompra;
import java.util.List;

/**
 *
 * @author Gabrielly Zeni Manthay
 */
public class DlgListadeCompra extends javax.swing.JDialog {

    /**
     * Creates new form DlgListadeCompra
     */
    
    private TableModelItemCompra tableModelItemCompra;    

    public DlgListadeCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tableModelItemCompra = new TableModelItemCompra();
        tblListadeCompra.setModel(tableModelItemCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpStatus = new javax.swing.ButtonGroup();
        pnlListadeCompra = new javax.swing.JPanel();
        pnlTabelaListadeCompra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadeCompra = new javax.swing.JTable();
        lblIngrediente = new javax.swing.JLabel();
        txtFldIngrediente = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        pnlStatus = new javax.swing.JPanel();
        rBtnComprado = new javax.swing.JRadioButton();
        rBtnNaoComprado = new javax.swing.JRadioButton();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlListadeCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Compras"));

        pnlTabelaListadeCompra.setLayout(new java.awt.BorderLayout());

        tblListadeCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingrediente", "Quantidade", "Status "
            }
        ));
        jScrollPane1.setViewportView(tblListadeCompra);

        pnlTabelaListadeCompra.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblIngrediente.setText("Ingrediente");

        lblQuantidade.setText("Quantidade");

        pnlStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        btnGrpStatus.add(rBtnComprado);
        rBtnComprado.setMnemonic('C');
        rBtnComprado.setText("Comprado");

        btnGrpStatus.add(rBtnNaoComprado);
        rBtnNaoComprado.setMnemonic('N');
        rBtnNaoComprado.setText("Não Comprado");

        javax.swing.GroupLayout pnlStatusLayout = new javax.swing.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBtnComprado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBtnNaoComprado)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnComprado)
                    .addComponent(rBtnNaoComprado))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListadeCompraLayout = new javax.swing.GroupLayout(pnlListadeCompra);
        pnlListadeCompra.setLayout(pnlListadeCompraLayout);
        pnlListadeCompraLayout.setHorizontalGroup(
            pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                        .addGroup(pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTabelaListadeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                                .addComponent(lblIngrediente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFldIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                        .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        pnlListadeCompraLayout.setVerticalGroup(
            pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIngrediente)
                    .addComponent(lblQuantidade)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlListadeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListadeCompraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabelaListadeCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListadeCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListadeCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirTabela(String ingrediente, int quantidade, char status) {
        ItemCompra item = new ItemCompra(ingrediente, quantidade, status);
        tableModelItemCompra.adicionar(item);
    }
        
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String ingrediente = txtFldIngrediente.getText(); 
        int quantidade = Integer.parseInt(spnQuantidade.getValue().toString()) ;
        char status = (char) btnGrpStatus.getSelection().getMnemonic();
        
        inserirTabela(ingrediente, quantidade, status);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void limparCampos() {
        txtFldIngrediente.setText( "" );
        spnQuantidade.setValue(0);
        btnGrpStatus.clearSelection();
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrpStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JPanel pnlListadeCompra;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JPanel pnlTabelaListadeCompra;
    private javax.swing.JRadioButton rBtnComprado;
    private javax.swing.JRadioButton rBtnNaoComprado;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTable tblListadeCompra;
    private javax.swing.JTextField txtFldIngrediente;
    // End of variables declaration//GEN-END:variables
}
