/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabrielly Zeni Manthay
 */
public class DlgCadastro extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadastro
     */
    public DlgCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroReceita = new javax.swing.JPanel();
        lblNomeReceita = new javax.swing.JLabel();
        txtFldNomeReceita = new javax.swing.JTextField();
        lblCategoriaReceita = new javax.swing.JLabel();
        cmbBCategoriaReceita = new javax.swing.JComboBox<>();
        lblIngredientes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAIngredientes = new javax.swing.JTextArea();
        lblMododePreparo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAMododePreparo = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCadastroReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Receita"));

        lblNomeReceita.setText("Nome da Receita");

        lblCategoriaReceita.setText("Categoria da Receita:");

        cmbBCategoriaReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblIngredientes.setText("Ingredientes:");

        txtAIngredientes.setColumns(20);
        txtAIngredientes.setRows(5);
        jScrollPane3.setViewportView(txtAIngredientes);

        lblMododePreparo.setText("Modo de Preparo:");

        txtAMododePreparo.setColumns(20);
        txtAMododePreparo.setRows(5);
        jScrollPane1.setViewportView(txtAMododePreparo);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroReceitaLayout = new javax.swing.GroupLayout(pnlCadastroReceita);
        pnlCadastroReceita.setLayout(pnlCadastroReceitaLayout);
        pnlCadastroReceitaLayout.setHorizontalGroup(
            pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroReceitaLayout.createSequentialGroup()
                        .addGroup(pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastroReceitaLayout.createSequentialGroup()
                                .addComponent(btnAdicionar)
                                .addGap(66, 66, 66)
                                .addComponent(btnCancelar))
                            .addGroup(pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCategoriaReceita)
                                .addComponent(lblIngredientes)
                                .addComponent(lblMododePreparo)
                                .addComponent(lblNomeReceita)
                                .addComponent(cmbBCategoriaReceita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldNomeReceita)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCadastroReceitaLayout.setVerticalGroup(
            pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCategoriaReceita)
                .addGap(9, 9, 9)
                .addComponent(cmbBCategoriaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngredientes)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMododePreparo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos() {
        txtFldNomeReceita.setText( "" );
        cmbBCategoriaReceita.setSelectedIndex(0);
        txtAIngredientes.setText("");
        txtAMododePreparo.setText("");
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String nomeReceita = txtFldNomeReceita.getText();
        String categoria = cmbBCategoriaReceita.getSelectedItem().toString();
        String ingredientes = txtAIngredientes.getText();
        String modoPreparo = txtAMododePreparo.getText();
        
        JOptionPane.showMessageDialog(this, "Receita Cadastrada Com Sucesso");
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbBCategoriaReceita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategoriaReceita;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblMododePreparo;
    private javax.swing.JLabel lblNomeReceita;
    private javax.swing.JPanel pnlCadastroReceita;
    private javax.swing.JTextArea txtAIngredientes;
    private javax.swing.JTextArea txtAMododePreparo;
    private javax.swing.JTextField txtFldNomeReceita;
    // End of variables declaration//GEN-END:variables
}
