/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viewer;

/**
 *
 * @author MTI
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCampos = new javax.swing.JPanel();
        pnlNovaReceita = new javax.swing.JPanel();
        btnCriarNovaReceita = new javax.swing.JButton();
        pnlListadeCompras = new javax.swing.JPanel();
        btnCriarListadeCompras = new javax.swing.JButton();
        pnlPesquisarReceita = new javax.swing.JPanel();
        btnPesquisarReceita = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNovaReceita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nova Receita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 1, 18))); // NOI18N

        btnCriarNovaReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnCriarNovaReceita.setText("Criar Nova Receita");
        btnCriarNovaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarNovaReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNovaReceitaLayout = new javax.swing.GroupLayout(pnlNovaReceita);
        pnlNovaReceita.setLayout(pnlNovaReceitaLayout);
        pnlNovaReceitaLayout.setHorizontalGroup(
            pnlNovaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNovaReceitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarNovaReceita)
                .addContainerGap())
        );
        pnlNovaReceitaLayout.setVerticalGroup(
            pnlNovaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNovaReceitaLayout.createSequentialGroup()
                .addComponent(btnCriarNovaReceita)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlListadeCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista De Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 1, 18))); // NOI18N

        btnCriarListadeCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnCriarListadeCompras.setText("Criar uma lista de compras");
        btnCriarListadeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarListadeComprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListadeComprasLayout = new javax.swing.GroupLayout(pnlListadeCompras);
        pnlListadeCompras.setLayout(pnlListadeComprasLayout);
        pnlListadeComprasLayout.setHorizontalGroup(
            pnlListadeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadeComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCriarListadeCompras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListadeComprasLayout.setVerticalGroup(
            pnlListadeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListadeComprasLayout.createSequentialGroup()
                .addComponent(btnCriarListadeCompras)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPesquisarReceita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar Receita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 1, 18))); // NOI18N

        btnPesquisarReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        btnPesquisarReceita.setText("Pesquisar Receita");
        btnPesquisarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisarReceitaLayout = new javax.swing.GroupLayout(pnlPesquisarReceita);
        pnlPesquisarReceita.setLayout(pnlPesquisarReceitaLayout);
        pnlPesquisarReceitaLayout.setHorizontalGroup(
            pnlPesquisarReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisarReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPesquisarReceita)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlPesquisarReceitaLayout.setVerticalGroup(
            pnlPesquisarReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisarReceitaLayout.createSequentialGroup()
                .addComponent(btnPesquisarReceita)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCamposLayout = new javax.swing.GroupLayout(pnlCampos);
        pnlCampos.setLayout(pnlCamposLayout);
        pnlCamposLayout.setHorizontalGroup(
            pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNovaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlListadeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPesquisarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        pnlCamposLayout.setVerticalGroup(
            pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlListadeCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNovaReceita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPesquisarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(pnlCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 120));

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela Login.jpeg"))); // NOI18N
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarListadeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarListadeComprasActionPerformed
        DlgListadeCompra objCom = new DlgListadeCompra(this, true);
        objCom.setVisible(true);
    }//GEN-LAST:event_btnCriarListadeComprasActionPerformed

    private void btnCriarNovaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarNovaReceitaActionPerformed
        DlgCadastro objCad = new DlgCadastro(this, true);
        objCad.setVisible(true);
    }//GEN-LAST:event_btnCriarNovaReceitaActionPerformed

    private void btnPesquisarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarReceitaActionPerformed
        DlgVerReceita objRec = new DlgVerReceita(this, true);
        objRec.setVisible(true);
    }//GEN-LAST:event_btnPesquisarReceitaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarListadeCompras;
    private javax.swing.JButton btnCriarNovaReceita;
    private javax.swing.JButton btnPesquisarReceita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlCampos;
    private javax.swing.JPanel pnlListadeCompras;
    private javax.swing.JPanel pnlNovaReceita;
    private javax.swing.JPanel pnlPesquisarReceita;
    // End of variables declaration//GEN-END:variables
}
